### ISSUE TITLE
Unknown Prop Warning

### ISSUE THREAD

**Issue by brandonfancher** [schneidmaster/react-bootstrap-maskedinput#1]
react-bootstrap-maskedinput 2.0
react 15.3.2
react-bootstrap 0.30.5

Getting [Unknown Prop Warning](https://facebook.github.io/react/warnings/unknown-prop.html) on props `componentClass` and `bsClass`.

Took a peek at the generated js. Maybe `this.props` instead of `props` is getting passed down?

**Comment by brandonfancher** [comment]
Sorry, react-bootstrap-maskedinput 0.2.0.

Looks like the for loop that creates the props object needs a bit of work too. I will submit a PR.

**Comment by schneidmaster** [comment]
Fixed in #2
