### ISSUE TITLE
It does not work with typescript

### ISSUE THREAD

**Issue by yardz** [schneidmaster/react-bootstrap-maskedinput#12]
It does not work with typescript because it does not have a @ types / react-bootstrap-maskedinput

**Comment by schneidmaster** [comment]
Hi there -- I'm happy to accept a PR if you'd like to add types for the module. You can also [declare types in your codebase for untyped npm modules](https://www.typescriptlang.org/docs/handbook/modules.html#working-with-other-javascript-libraries).
