### ISSUE TITLE
Version that works with react-bootstrap 1.1.1

### ISSUE THREAD

**Issue by mikecole** [schneidmaster/react-bootstrap-maskedinput#14]
Is it just me or does this not work with versions of react-bootstrap > 1? 

Error:
`
Uncaught TypeError: Super expression must either be null or a function, not object
    at _inherits (index.js:25)
    at index.js:28
    at Object../node_modules/react-bootstrap-maskedinput/lib/index.js (index.js:46)
`

**Comment by schneidmaster** [comment]
Published 0.5.0 which supports react-bootstrap 1.x.

To be honest, I am probably going to deprecate this package soon -- it used to have a lot more logic, but has gotten pointlessly simple now that current versions of react-bootstrap make it easy to swap in a different component. This is literally all there is to it:

https://github.com/schneidmaster/react-bootstrap-maskedinput/blob/c4cb7519e3fa4ea507b7598f7295f8362e11229e/src/index.js#L1-L7

**Comment by mikecole** [comment]
Thank you very much for the quite turn around time. I greatly appreciate it.
