### ISSUE TITLE
Ref not working

### ISSUE THREAD

**Issue by Fornori** [schneidmaster/react-bootstrap-maskedinput#4]
Hello. How can i get value of the MaskedFormControl?

` <MaskedFormControl
                                    type="text"
                                    placeholder="Input phone"
                                    mask='(111)-111-11-11'
                                    ref={(ref) => this.txtPhone = ref}
                                />`

this.txtPhone.value always return undefined

**Comment by schneidmaster** [comment]
Hi -- this is because of the `FormControl` abstraction used by `react-bootstrap`. In your example, you would need to do `ReactDOM.findDOMNode(this.txtPhone).value`. See [here](https://github.com/react-bootstrap/react-bootstrap/issues/1850) for further reading.
