### ISSUE TITLE
The maskfield not correcly work on the Android device

### ISSUE THREAD

**Issue by Fornori** [schneidmaster/react-bootstrap-maskedinput#5]
Create maksuinput 
<MaskedFormControl
                                        type="text"
                                        mask='(111)111-11-11'
                                        value={this.state.phone}
                                        onChange={this.handleChangeUserPhone}
                                    />

And on the An dorid phone it's not correcly work after i remove one of the number inside input

**Comment by schneidmaster** [comment]
Hi there -- I'll need more information to be able to reproduce and perhaps fix the issue.

* What is the expected behavior and what is the actual behavior

* What code are you using to initialize the component (e.g. copy and paste the `< MaskedFormControl>` from your code)

* Which Android device and OS version

* Which browser and version

Thanks.

**Comment by schneidmaster** [comment]
Closing this for now, will reopen if I get a more detailed bug report.

**Comment by danielmcleod** [comment]
I am having this issue on android using chrome.

Steps to reproduce:
select/click on masked input
try to enter a number
the keyboard switches to Letters and nothing can be entered, even if you switch back to numbers, the process is repeated. The placeholder remains in the input.

When using the remote debugging tools, I was able to enter 1 or more numbers from my desktop and then complete the entry via my phone. However, I had to enter an extra number to skip past the dash.

Here is my code below:

`                                   <MaskedFormControl
                                        type="text"
                                        placeholder="#####-###-###"
                                        onChange={this.requestNumberChange}
                                        mask="11111-111-111"
                                        placeholderChar="#"
                                        value={requestNumber}
                                    />`

Please let me know if you have any suggestions.
Thanks,
Daniel

**Comment by schneidmaster** [comment]
@danielmcleod Thanks for the detailed report. I suspect it's an underlying problem with `react-maskedinput` -- this library is a single class that merely renders a masked input so there's not a whole lot of surface for me to introduce bugs. Does [this report](https://github.com/insin/react-maskedinput/issues/86) seem like your issue? (I also found [this report](https://github.com/insin/react-maskedinput/issues/95) for Android Firefox).

**Comment by danielmcleod** [comment]
@schneidmaster thank you for responding so quickly. It does appear this is related to react-maskedinput. I am experiencing both of those issues.
