### ISSUE TITLE
`react-maskedinput` updated to 4.0.0

### ISSUE THREAD

**Issue by DevanB** [schneidmaster/react-bootstrap-maskedinput#6]
Now that `react-maskedinput` has been updated (and finally removed `createClass`), will we see an update to `react-bootstrap-maskedinput` soon? I'm hoping the new version fixed the Android related problems also! 💯

**Comment by schneidmaster** [comment]
Thanks for letting me know the new release is out. I'll have to test for any new compatibility problems and then I can relax the version and cut a new release.
